# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: tome

before:
  hooks:
    - go mod tidy

builds:
  - id: tome
    main: .
    binary: tome
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/kennyg/tome/cmd.Version={{.Version}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: kennyg
    name: tome
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

# Note: Homebrew formula is maintained manually in kennyg/homebrew-tap
# Building from source avoids macOS notarization requirements
